theme: jekyll-theme-slate

title       : Darcie Chart
local       : "pl-PL"
name        : Darcie Chart
description : "Prosta, reactowa aplikacja do edycji wykresów"

author:
  name             : Patryk Cholewa i Paweł Zych